const data = [
  {
    id: "1",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Nike Air Monarch IV",
    prevPrice: "$140,00",
    newPrice: "$200",
    company: "Nike", 
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
  {
    id: "2",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Nike Air Vapormax Plus",  
    prevPrice: "$140,00",
    newPrice: "$200",
    company: "Nike",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },

  {
    id: "3",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Nike Waffle One Sneaker", 
    prevPrice: "$140,00",
    newPrice: "$200",
    company: "Nike",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
  {
    id: "4",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Nike Running Shoe",
    prevPrice: "$140,00",
    newPrice: "$200",
    company: "Adidas",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
  {
    id: "5",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Flat Slip On Pumps",
    prevPrice: "$140,00",
    newPrice: "$200",
    company: "Vans",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
  {
    id: "6",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Knit Ballet Flat",
    prevPrice: "$140,00",
    newPrice: "$50",
    company: "Adidas",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },

  {
    id: "7",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Loafer Flats",
    prevPrice: "$140,00",
    newPrice: "$50",
    company: "Vans",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },

  {
    id: "8",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Nike Zoom Freak",
    prevPrice: "$140,00",
    newPrice: "$200",
    company: "Nike",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },

  {
    id: "9",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Nike Men's Sneaker",
    prevPrice: "$140,00",
    newPrice: "$200",
    company: "Adidas",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },

  {
    id: "10",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "PUMA BLACK-OCE",
    prevPrice: "$140,00",
    newPrice: "$150",
    company: "Puma",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
  {
    id: "11",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Pacer Future Sneaker",
    prevPrice: "$140,00",
    newPrice: "$150",
    company: "Puma",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
  {
    id: "12",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Unisex-Adult Super",
    prevPrice: "$140,00",
    newPrice: "$150",
    company: "Puma",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
  {
    id: "13",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Roma Basic Sneaker",
    prevPrice: "$140,00",
    newPrice: "$150",
    company: "Puma",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
  {
    id: "14",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Pacer Future Doubleknit",
    prevPrice: "$140,00",
    newPrice: "$150",
    company: "Puma",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },

  {
    id: "15",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Fusion Evo Golf Shoe",
    prevPrice: "$140,00",
    newPrice: "$100",
    company: "Puma",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
  {
    id: "16",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Rainbow Chex Skate",
    prevPrice: "$140,00",
    newPrice: "$100",
    company: "Vans",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
  {
    id: "17",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Low-Top Trainers",
    prevPrice: "$140,00",
    newPrice: "$100",
    company: "Vans",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
  {
    id: "18",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Vans Unisex Low-Top",
    prevPrice: "$140,00",
    newPrice: "$100",
    company: "Vans",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
  {
    id: "19",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Classic Bandana Sneakers",
    prevPrice: "$140,00",
    newPrice: "$50",
    company: "Nike",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
  {
    id: "20",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Chunky High Heel",
    prevPrice: "$140,00",
    newPrice: "$50",
    company: "Vans",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
  {
    id: "21",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Slip On Stiletto High Heel",
    prevPrice: "$140,00",
    newPrice: "$100",
    company: "puma",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
  {
    id: "22",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "DREAM PAIRS Court Shoes",
    prevPrice: "$140,00",
    newPrice: "$150",
    company: "Nike",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
  {
    id: "23",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Nike Air Vapormax Plus",
    prevPrice: "$140,00",
    newPrice: "$200",
    company: "Nike",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },

  {
    id: "24",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Low Mid Block Heels",
    prevPrice: "$140,00",
    newPrice: "$200",
    company: "Nike",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
  {
    id: "25",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Chunky High Heel",
    prevPrice: "$140,00",
    newPrice: "$50",
    company: "Adidas",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
  {
    id: "26",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Amore Fashion Stilettos",
    prevPrice: "$140,00",
    newPrice: "$150",
    company: "Adidas",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
  {
    id: "27",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Bridal Sandals Glitter",
    prevPrice: "$140,00",
    newPrice: "$50",
    company: "Adidas",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
  {
    id: "28",
    img: "https://www.dummyimage.com/760x500.jpg",
    title: "Wedding Prom Bridal",
    prevPrice: "$140,00",
    newPrice: "$50",
    company: "Adidas",
    description: "These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they will withstand everything the weather can offer.",
  },
];

export default data;
